const { getPeople } = require('./services');

async function main() {
  try {
  } catch (error) {
    console.log('There is a error', error);
  }
}

main();
